package:
  name: astral
  version: 5.7.3
build:
  number: 1
source:
  path: ../../lib/ASTRAL-5.7.3
about:
  summary: ASTRAL is a tool for estimating an unrooted species tree given a set of unrooted gene trees.
  license: Apache-2.0